name: Linux Tests (Docker)

on:
  workflow_dispatch:    # Manual trigger
    branches:
      - 'master'

#  push:
#    paths-ignore:
#      - '**.md'
#      - '**.yml'
#
#  pull_request:
#    paths-ignore:
#      - '**.md'
#      - '**.yml'

jobs:
  vm:
    runs-on: ubuntu-latest
    container:
      image: luismiaresse/pricelist-fetcher:latest
      options: --user root
    steps:
      - name: Install python dependencies
        working-directory: /home/luismi/pricelist-fetcher
        run: |
          pip3 install -r requirements.txt pytest
      - name: Test with pytest
        working-directory: /home/luismi/pricelist-fetcher
        run: |
          python3 -m pytest
